apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: limascloud/node
          imagePullPolicy: IfNotPresent
          args: ["dist/apps/api/main"]
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100